# Color scheme

import = [
    "~/.config/alacritty/themes/netheme.toml"
]

# Display

[window]
dynamic_padding = true
dynamic_title = true

[window.dimensions]
columns = 120
lines = 35

[window.padding]
x = 6
y = 6

[font]
size = 12.0

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "On"

# Behavior

[selection]
save_to_clipboard = true
