root: true
env:
    es2022: true
extends:
    - eslint:recommended
    - plugin:prettier/recommended
parserOptions:
    ecmaVersion: latest
    sourceType: module
rules:
    prettier/prettier:
        - warn
    no-unused-vars:
        - off
overrides:
    - files:
          - "**/*.ts"
      extends:
          - eslint:recommended
          - plugin:@typescript-eslint/recommended
          - plugin:prettier/recommended
      rules:
          prettier/prettier:
              - warn
          "@typescript-eslint/no-unused-vars":
              - off
