[colors.primary]
background = "#1C1E26"
foreground = "#D5D8DA"

[colors.normal]
black = "#2E303E"
red = "#E95678"
green = "#27D796"
yellow = "#FAB795"
blue = "#26BBD9"
magenta = "#B877DB"
cyan = "#25B2BC"
white = "#CCCCCC"

[colors.bright]
black = "#767676"
red = "#F09383"
green = "#09F7A0"
yellow = "#FAC29A"
blue = "#3FC6DE"
magenta = "#F075B7"
cyan = "#6BE6E6"
white = "#F2F2F2"
