# Monokai theme from https://github.com/yosukes-dev/monokai-windows-terminal

[colors.primary]
background = "#1A1A1A"
foreground = "#F8F8F2"

[colors.normal]
black = "#1B1D1E"
red = "#F92672"
green = "#82B414"
yellow = "#FD971F"
blue = "#465457"
magenta = "#8C54FE"
white = "#CCCCC6"
cyan = "#56C2D6"

[colors.bright]
black = "#505354"
red = "#FF5995"
green = "#B6E354"
yellow = "#FEED6C"
blue = "#899CA1"
magenta = "#9E6FFE"
white = "#F8F8F2"
cyan = "#8CEDFF"
