[colors.primary]
background = "#1A1C22"
foreground = "#B7C2C8"

[colors.normal]
black = "#20232A"
red = "#D9526B"
green = "#7CB854"
yellow = "#F7A074"
blue = "#3D90E3"
magenta = "#C388EB"
cyan = "#52AEBA"
white = "#959A9E"

[colors.bright]
black = "#5F6774"
red = "#F8929D"
green = "#BCDE79"
yellow = "#F9C097"
blue = "#85BDF6"
magenta = "#DDADF5"
cyan = "#95E4DD"
white = "#DDEBF2"
