[colors.primary]
background = "#171A22"
foreground = "#B7C2C8"

[colors.normal]
black = "#20232B"
blue = "#4788F0"
cyan = "#49B2BB"
green = "#56B877"
magenta = "#AF6ADB"
red = "#DA5261"
white = "#8B909D"
yellow = "#DB8878"

[colors.bright]
black = "#555A66"
blue = "#81B5FF"
cyan = "#69F3FF"
green = "#A7FA9C"
magenta = "#D9A1FF"
red = "#fa788e"
white = "#DDEBF2"
yellow = "#F9C097"
