# Vivid black bearded theme from VSCode

[colors.primary]
background = "#141417"
foreground = "#EEEEEE"

[colors.normal]
black = "#242427"
blue = "#238DD6"
cyan = "#14B5A7"
green = "#2C904D"
magenta = "#A95EFF"
red = "#D62C2C"
white = "#CBCBCB"
yellow = "#FF7135"

[colors.bright]
black = "#666666"
blue = "#28A9FF"
cyan = "#14E5D4"
green = "#42DD76"
magenta = "#E66DFF"
red = "#FF478D"
white = "#FFFFFF"
yellow = "#FFB638"
