# Vivid black bearded theme from VSCode

[colors.primary]
background = "#141417"
foreground = "#EEEEEE"

[colors.normal]
black = "#242427"
red = "#D62C2C"
green = "#2C904D"
yellow = "#FF7135"
blue = "#238DD6"
magenta = "#A95EFF"
white = "#CBCBCB"
cyan = "#14B5A7"

[colors.bright]
black = "#666666"
red = "#FF478D"
green = "#42DD76"
yellow = "#FFB638"
blue = "#28A9FF"
magenta = "#E66DFF"
white = "#FFFFFF"
cyan = "#14E5D4"
